### ISSUE TITLE
Feature request: Select monitor

### ISSUE THREAD

**Issue by VerstandInvictus** [hamodyk/Corsair-Ambience#1]
First: This is awesome and you're probably going to be singlehandedly responsible for me spending way too much on Corsair RGB ecosystem products.

As a feature request: I usually game on one monitor with various browsers/chats/etc open on three other monitors. Would it be possible to "pin" the ambience to the gaming monitor only, so that the lighting only reflects the average color in-game?

**Comment by hamodyk** [comment]
@VerstandInvictus hmmm I'm not sure but I'll definitely look into it

**Comment by hamodyk** [comment]
@VerstandInvictus just added this feature to the code. You'll see it in the upcoming release!
