### ISSUE TITLE
Feature request: Choose between single or multi color

### ISSUE THREAD

**Issue by matteobatazzi** [hamodyk/Corsair-Ambience#2]
First of all, thank you very much for this tool, I love it! 

In the version 1.3 there was only one color taking the full keyboard and it was the perfect behavior for me, really happy with it. With the 2.0 there are multi color (and multiple keys can have the light turn off because of the black color), is it possible to add an option to choose from single or multi color?

Thanks again!

**Comment by hamodyk** [comment]
Hi! Glad you're enjoying it! Yes that option is available in 2.0, just go to the settings file and set KeyboardZoneColoring and MousePadZoneColoring to off

**Comment by matteobatazzi** [comment]
Perfect, thank you very much!
