### ISSUE TITLE
Showing different color as compared to Armoury Crate's calculated average color

### ISSUE THREAD

**Issue by ZaifSenpai** [hamodyk/Corsair-Ambience#4]
The rest of the ARGB on my system is being controlled by Armoury Crate but unfortunately, it is unable to control the RAM so I am trying out this software.

The problem is that I set the "Adaptive Color" effect from Armoury Create and choose "Average color in the detection area" (Detection area is my whole primary display). Now I am using Corsair Ambience for changing colors of RAM which is not showing the same color as other LEDs.

Screenshot used for testing:
![Primary Display](https://i.imgur.com/1SZL6AD.png)

Lights:
![Lights](https://i.imgur.com/vpg2ads.jpg)

Here are settings from Armoury Crate:
![Armoury Crate](https://i.imgur.com/VVFDagu.png)

Settings on Corsair Ambience:
![Corsair Ambience](https://i.imgur.com/jW1isRU.png)

**Comment by hamodyk** [comment]
Hi @ZaifSenpai, can you please try to turn off the "FilterBadColors" in the settings?

In this mode the app will remove extremely bright and dark colors because they ruin the experience as can be seen here: https://github.com/hamodyk/Corsair-Ambience/blob/master/Corsair%20Ambience/Ambience.cpp#L165

**Comment by ZaifSenpai** [comment]
Thanks, it worked.
I did it and now it is a lot better. I also had to decrease the brightness of modules to 40% and now it is matching the colors of other devices.
